(function (cjs, an) {

var p; // shortcut to reference prototypes
var lib={};var ss={};var img={};
lib.ssMetadata = [
		{name:"RECOVER_пластинка_atlas_1", frames: [[946,83,47,81],[946,166,47,81],[946,747,36,81],[946,249,47,81],[946,332,47,81],[946,415,47,81],[946,498,47,81],[984,747,36,81],[946,581,47,81],[946,664,47,81],[946,0,188,81],[0,1356,868,96],[870,1356,868,96],[0,0,944,1354]]},
		{name:"RECOVER_пластинка_atlas_2", frames: [[0,0,1440,1440]]}
];


(lib.AnMovieClip = function(){
	this.actionFrames = [];
	this.ignorePause = false;
	this.gotoAndPlay = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndPlay.call(this,positionOrLabel);
	}
	this.play = function(){
		cjs.MovieClip.prototype.play.call(this);
	}
	this.gotoAndStop = function(positionOrLabel){
		cjs.MovieClip.prototype.gotoAndStop.call(this,positionOrLabel);
	}
	this.stop = function(){
		cjs.MovieClip.prototype.stop.call(this);
	}
}).prototype = p = new cjs.MovieClip();
// symbols:



(lib.CachedBmp_13 = function() {
	this.initialize(ss["RECOVER_пластинка_atlas_1"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_12 = function() {
	this.initialize(ss["RECOVER_пластинка_atlas_1"]);
	this.gotoAndStop(1);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_11 = function() {
	this.initialize(ss["RECOVER_пластинка_atlas_1"]);
	this.gotoAndStop(2);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_10 = function() {
	this.initialize(ss["RECOVER_пластинка_atlas_1"]);
	this.gotoAndStop(3);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_9 = function() {
	this.initialize(ss["RECOVER_пластинка_atlas_1"]);
	this.gotoAndStop(4);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_8 = function() {
	this.initialize(ss["RECOVER_пластинка_atlas_1"]);
	this.gotoAndStop(5);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_7 = function() {
	this.initialize(ss["RECOVER_пластинка_atlas_1"]);
	this.gotoAndStop(6);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_6 = function() {
	this.initialize(ss["RECOVER_пластинка_atlas_1"]);
	this.gotoAndStop(7);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_5 = function() {
	this.initialize(ss["RECOVER_пластинка_atlas_1"]);
	this.gotoAndStop(8);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_4 = function() {
	this.initialize(ss["RECOVER_пластинка_atlas_1"]);
	this.gotoAndStop(9);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_3 = function() {
	this.initialize(ss["RECOVER_пластинка_atlas_1"]);
	this.gotoAndStop(10);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_2 = function() {
	this.initialize(ss["RECOVER_пластинка_atlas_1"]);
	this.gotoAndStop(11);
}).prototype = p = new cjs.Sprite();



(lib.CachedBmp_1 = function() {
	this.initialize(ss["RECOVER_пластинка_atlas_1"]);
	this.gotoAndStop(12);
}).prototype = p = new cjs.Sprite();



(lib.ручка = function() {
	this.initialize(ss["RECOVER_пластинка_atlas_1"]);
	this.gotoAndStop(13);
}).prototype = p = new cjs.Sprite();



(lib.Bitmap1 = function() {
	this.initialize(ss["RECOVER_пластинка_atlas_2"]);
	this.gotoAndStop(0);
}).prototype = p = new cjs.Sprite();
// helper functions:

function mc_symbol_clone() {
	var clone = this._cloneProps(new this.constructor(this.mode, this.startPosition, this.loop, this.reversed));
	clone.gotoAndStop(this.currentFrame);
	clone.paused = this.paused;
	clone.framerate = this.framerate;
	return clone;
}

function getMCSymbolPrototype(symbol, nominalBounds, frameBounds) {
	var prototype = cjs.extend(symbol, cjs.MovieClip);
	prototype.clone = mc_symbol_clone;
	prototype.nominalBounds = nominalBounds;
	prototype.frameBounds = frameBounds;
	return prototype;
	}


(lib.Tween9 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Bitmap1();
	this.instance.setTransform(-190.8,-190.8,0.265,0.265);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-190.8,-190.8,381.6,381.6);


(lib.Symbol1 = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	// Layer_1
	this.instance = new lib.Bitmap1();
	this.instance.setTransform(-190.8,-190.8,0.265,0.265);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(1));

	this._renderFirstFrame();

}).prototype = getMCSymbolPrototype(lib.Symbol1, new cjs.Rectangle(-190.8,-190.8,381.6,381.6), null);


// stage content:
(lib.RECOVER_пластинка = function(mode,startPosition,loop,reversed) {
if (loop == null) { loop = true; }
if (reversed == null) { reversed = false; }
	var props = new Object();
	props.mode = mode;
	props.startPosition = startPosition;
	props.labels = {};
	props.loop = loop;
	props.reversed = reversed;
	cjs.MovieClip.apply(this,[props]);

	this.actionFrames = [0,24,49,208];
	// timeline functions:
	this.frame_0 = function() {
		/* Click to Go to Web Page
		Clicking on the specified symbol instance loads the URL in a new browser window.
		
		Instructions:
		1. Replace http://www.adobe.com with the desired URL address.
		   Keep the quotation marks ("").
		*/
		
		this.movieClip_1.addEventListener("click", fl_ClickToGoToWebPage);
		
		function fl_ClickToGoToWebPage() {
			window.open("https://nervy-concert.ru/", "_blank");
		}
	}
	this.frame_24 = function() {
		playSound("_04715");
	}
	this.frame_49 = function() {
		playSound("nazvonokcom_nervyjarcheitepleemp3copy");
	}
	this.frame_208 = function() {
		playSound("_04715mp3copy");
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).call(this.frame_0).wait(24).call(this.frame_24).wait(25).call(this.frame_49).wait(159).call(this.frame_208).wait(21));

	// Layer_9
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#333333").s().p("Ag9A8QgZgZAAgjQAAgjAZgYQAagZAjAAQAkAAAaAZQAZAYAAAjQAAAjgZAZQgaAZgkAAQgjAAgagZg");
	this.shape.setTransform(371.475,682.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#333333").s().p("AiRCOQg8g7AAhTQAAhTA8g6QA8g7BWAAQBVAAA8A7QA8A6AABTQAABTg8A7Qg8A7hVAAQhWAAg8g7g");
	this.shape_1.setTransform(371.525,682.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#333333").s().p("AjlDgQhgheAAiCQAAiEBghbQBfhdCHAAQCGAABfBdQBgBbAACEQAACChgBeQhfBdiGAAQiHAAhfhdg");
	this.shape_2.setTransform(371.575,682.525);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#333333").s().p("Ak6EyQiCh/AAizQAAi0CCh9QCCh/C5AAQC3AACDB/QCCB9AAC0QAACziCB/QiDCAi3gBQi5ABiCiAg");
	this.shape_3.setTransform(371.625,682.5);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#333333").s().p("AmOGEQiliiAAjiQAAjlClieQCliiDqABQDpgBClCiQClCeAADlQAADiilCiQilChjpABQjqgBilihg");
	this.shape_4.setTransform(371.65,682.5);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#333333").s().p("AktEmQh9h7AAirQAAitB9h4QB8h6CyAAQCwAAB9B6QB9B4AACtQAACrh9B7Qh9B6iwAAQiyAAh8h6g");
	this.shape_5.setTransform(371.65,682.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#333333").s().p("AjMDIQhVhTAAh1QAAh1BVhRQBUhUB4AAQB4AABVBUQBVBRAAB1QAAB1hVBTQhVBSh4AAQh4AAhUhSg");
	this.shape_6.setTransform(371.65,682.5);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#333333").s().p("AhrBqQgtgtAAg9QAAg9AtgrQAtgsA+AAQBAAAAsAsQAtArAAA9QAAA9gtAtQgsArhAAAQg+AAgtgrg");
	this.shape_7.setTransform(371.6,682.5);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#333333").s().p("AgKALQgFgFAAgGQAAgGAFgEQAEgEAGgBQAGABAGAEQAEAEAAAGQAAAGgEAFQgGAFgGAAQgGAAgEgFg");
	this.shape_8.setTransform(371.6,682.5);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#333333").s().p("AgDAEQAAAAgBgBQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAAAQAAgBAAAAQABgBAAAAQABgBAAAAQAAgBABAAQAAAAABgBQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABQABAAAAABQAAAAABABQAAAAAAABQAAAAAAAAQAAABAAAAQAAABAAAAQgBABAAAAQAAABgBAAQAAAAgBABQAAAAgBAAQAAABgBAAQAAAAgBAAQAAAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAg");
	this.shape_9.setTransform(371.25,682.55);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#333333").s().p("AhLBPQgmgeAAgxQAAgwAmgoQAdgeAuAAQAwAAAlAeQAdAoAAAwQAAAxgdAeQglAogwAAQguAAgdgog");
	this.shape_10.setTransform(371.35,682.925);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#333333").s().p("AiTCaQhKg6AAhgQAAhfBKhNQA3g6BcAAQBdAABJA6QA3BNAABfQAABgg3A6QhJBNhdAAQhcAAg3hNg");
	this.shape_11.setTransform(371.45,683.3);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#333333").s().p("AjbDlQhuhWAAiPQAAiOBuhzQBThWCIAAQCJAABuBWQBSBzAACOQAACPhSBWQhuBziJAAQiIAAhThzg");
	this.shape_12.setTransform(371.55,683.675);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#333333").s().p("AkiEwQiShxAAi/QAAi9CSiYQBthyC1AAQC2AACSByQBtCYAAC9QAAC/htBxQiSCYi2AAQi1AAhtiYg");
	this.shape_13.setTransform(371.65,684.05);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#333333").s().p("AlqF7Qi2iOAAjtQAAjsC2i9QCIiPDiAAQDjAAC2CPQCIC9AADsQAADtiICOQi2C+jjAAQjiAAiIi+g");
	this.shape_14.setTransform(371.75,684.425);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#333333").s().p("AkjExQiThyAAi/QAAi+CTiYQBthzC2AAQC2AACTBzQBtCYABC+QgBC/htByQiTCZi2AAQi2AAhtiZg");
	this.shape_15.setTransform(371.75,684.425);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#333333").s().p("AjdDnQhvhWAAiRQAAiQBvhzQBUhXCJAAQCLAABvBXQBTBzAACQQAACRhTBWQhvB0iLAAQiJAAhUh0g");
	this.shape_16.setTransform(371.75,684.425);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#333333").s().p("AiWCdQhLg6AAhjQAAhhBLhPQA5g7BdAAQBeAABMA7QA4BPAABhQAABjg4A6QhMBPheAAQhdAAg5hPg");
	this.shape_17.setTransform(371.75,684.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#333333").s().p("AhPBTQgogfAAg0QAAgzAogpQAeggAxAAQAyAAAoAgQAeApAAAzQAAA0geAfQgoAqgyAAQgxAAgegqg");
	this.shape_18.setTransform(371.75,684.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#333333").s().p("AgIAJQgFgDABgGQgBgFAFgEQADgEAFAAQAFAAAFAEQAEAEAAAFQAAAGgEADQgFAFgFAAQgFAAgDgFg");
	this.shape_19.setTransform(371.75,684.4);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape}]},24).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).to({state:[{t:this.shape_4}]},1).to({state:[{t:this.shape_5}]},1).to({state:[{t:this.shape_6}]},1).to({state:[{t:this.shape_7}]},1).to({state:[{t:this.shape_8}]},1).to({state:[]},1).to({state:[{t:this.shape_9}]},175).to({state:[{t:this.shape_10}]},1).to({state:[{t:this.shape_11}]},1).to({state:[{t:this.shape_12}]},1).to({state:[{t:this.shape_13}]},1).to({state:[{t:this.shape_14}]},1).to({state:[{t:this.shape_15}]},1).to({state:[{t:this.shape_16}]},1).to({state:[{t:this.shape_17}]},1).to({state:[{t:this.shape_18}]},1).to({state:[{t:this.shape_19}]},1).wait(11));

	// ручка
	this.instance = new lib.ручка();
	this.instance.setTransform(287.4,335.15,0.1702,0.1748,142.809);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(40).to({rotation:147.055,x:290.55,y:344.45},0).wait(1).to({rotation:151.7724,x:293.2,y:355},0).wait(1).to({scaleY:0.1747,rotation:156.0111,x:294.85,y:364.65},0).wait(1).to({rotation:160.2217,x:295.8,y:374.35},0).wait(1).to({rotation:164.6663,x:296.05,y:384.6},0).wait(1).to({rotation:168.6469,x:295.55,y:393.8},0).wait(1).to({scaleX:0.1701,rotation:173.0922,x:294.3,y:404},0).wait(2).to({scaleX:0.1702,scaleY:0.1748,rotation:172.808,x:294.35,y:403.35},0).wait(181));

	// пластинка
	this.movieClip_1 = new lib.Symbol1();
	this.movieClip_1.name = "movieClip_1";
	this.movieClip_1.setTransform(369.8,263.8);

	this.instance_1 = new lib.Tween9("synched",0);
	this.instance_1.setTransform(369.8,263.8);
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.movieClip_1}]}).to({state:[{t:this.instance_1}]},49).to({state:[{t:this.instance_1}]},85).to({state:[{t:this.instance_1}]},84).wait(11));
	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(49).to({_off:false},0).to({rotation:360},85).to({rotation:720},84).wait(11));

	// плэй
	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#333333").s().p("AirjOIFXDOIlXDPg");
	this.shape_20.setTransform(378,681.325);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#333333").s().p("AA9EaIAAozIB0AAIAAIzgAiwEaIAAozIB0AAIAAIzg");
	this.shape_21.setTransform(372.1,682.275);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#333333").s().p("AjQkcIGhEMImhEtg");
	this.shape_22.setTransform(375.875,680.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_20}]}).to({state:[{t:this.shape_21}]},28).to({state:[{t:this.shape_22}]},185).to({state:[{t:this.shape_22}]},5).wait(11));

	// кнопки
	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f().s("#333333").ss(2,1,1).p("AuTAAQAACThoBoQhoBoiTAAQiUAAhohoQhnhoAAiTQAAiSBnhoQBohoCUAAQCTAABoBoQBoBoAACSgAIhAAQAADjigCgQigChjiAAQjjAAihihQigigAAjjQAAjiCgihQChigDjAAQDiAACgCgQCgChAADigAZaAAQAACThoBoQhoBoiTAAQiTAAhohoQhohoAAiTQAAiSBohoQBohoCTAAQCTAABoBoQBoBoAACSg");
	this.shape_23.setTransform(371.875,682.8);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#333333").s().p("AVLBhIgOAAIgBAAIAAheIiKBWIAAitICKBUIAAhdIAAgDIAPAAIAAAAIAADBgA1KBhIAAjBIAPAAIAABgIB7hLIAPgJIAACtIgPgJIh7hNIAABeg");
	this.shape_24.setTransform(372.15,683.425);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#CCCCCC").s().p("AmFGDQigigAAjjQAAjiCgihQChigDjAAQDiAACgCgQCgChAADiQAADjigCgQigChjigBQjjABihihgAP8D7QhohoAAiTQAAiSBohoQBohoCTAAQCTAABoBoQBoBoAACSQAACThoBoQhoBoiTAAQiTAAhohogASbDOIClhnIANAAIAAA4IAsAAIAAhcIBgg8Ihgg6IAAheIgsAAIAAA3IgOAAIAAADIikhkIAAAPIgYgPIAAAiIg3giIAAGJIA3gjIAAAjIAYgPgA3yD7QhnhoAAiTQAAiSBnhoQBohoCUAAQCTAABoBoQBoBoAACSQAACThoBoQhoBoiTAAQiUAAhohogAy9BWIAAARIAPAAIAAgHIAAiuIAAgMIgPAAIAAAWIh7BKIAAhgIgPAAIAADBIAPAAIAAheg");
	this.shape_25.setTransform(371.875,682.8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23}]}).to({state:[{t:this.shape_25},{t:this.shape_24},{t:this.shape_23}]},218).wait(11));

	// название
	this.instance_2 = new lib.CachedBmp_1();
	this.instance_2.setTransform(158.45,529.35,0.5,0.5);

	this.instance_3 = new lib.CachedBmp_2();
	this.instance_3.setTransform(158.45,529.35,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2}]}).to({state:[{t:this.instance_3}]},218).wait(11));

	// время
	this.instance_4 = new lib.CachedBmp_3();
	this.instance_4.setTransform(316.9,468.4,0.5,0.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#333333").s().p("AEoBWQgSgcAAg6QAAg5ATgbQASgdAnAAQAnAAASAdQASAcAAA4QAAA6gSAcQgTAcgmAAQgnAAgTgcgAFLhSQgJAFgFAMQgFAKgCASQgCASAAATQAAAXACAPQABAQAGAMQAEAMAJAFQAJAHAPAAQAOAAAJgHQAJgFAFgMQAFgLACgRQABgQAAgWQAAgWgBgQQgCgQgFgLQgGgMgIgFQgJgHgOAAQgOAAgJAHgAmaBWQgSgcAAg6QAAg5ASgbQASgdAnAAQAoAAASAdQASAcAAA4QAAA6gTAcQgSAcgnAAQgnAAgSgcgAl3hSQgKAFgFAMQgFAKgCASQgBASAAATQAAAXABAPQACAQAFAMQAFAMAJAFQAJAHAOAAQAOAAAJgHQAJgFAFgMQAFgLACgRQACgQAAgWQAAgWgCgQQgCgQgFgLQgFgMgJgFQgJgHgOAAQgOAAgIAHgABsBtIAAgWIAuAAIAAiSIguAAIAAgUIAUgBQALgCAFgCQAHgEAEgFQAEgHAAgJIAXAAIAADEIAtAAIAAAWgAgRBtIAAgpIAiAAIAAApgAjqBtIAAgeIAfgbQAPgNANgNQAdgbAKgQQAKgQAAgSQAAgRgLgKQgLgJgUgBQgNAAgQAGQgPAEgPAJIgCAAIAAgeQALgFARgEQARgEARgBQAhAAATAQQATAQAAAcQAAANgDALQgDAKgGAKQgGAJgIAIIgSATQgQAQgRAOIgfAbIB1AAIAAAZgAgRgMIAAgqIAiAAIAAAqg");
	this.shape_26.setTransform(363.825,489.65);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#333333").s().p("AmZBWQgSgcAAg6QAAg5ATgbQASgdAnAAQAnAAASAdQASAcAAA4QAAA6gSAcQgTAcgmAAQgnAAgTgcgAl2hSQgJAFgMAoQgCASAAATQAAAXACAPQABAQAGAMQAEAMAJAFQAJAHAPAAQAOAAAJgHQAJgFAFgMQAFgLACgRQABgQAAgWQAAgWgBgQQgCgQgFgLQgGgMgIgFQgJgHgOAAQgOAAgJAHgABuBtIAAgWIAtAAIAAiSIgtAAIAAgUIAUgBQAWgIAEgFQAEgHABgJIAXAAIAADEIAsAAIAAAWgAgPBtIAAgpIAiAAIAAApgAjpBtIAAgeIAfgbQAQgNANgNQAcgbAKgQQALgQAAgSQgXglgUAAQgNAAgPAGQgQAEgPAJIgBgeQAKgFASgEQARgEAQgBQAiAAATAQQATAQAAAcQAAANgDALQgEAKgGAKQgFAJgIAIIgTATQgPAQgRAOIgfAbIB1AAIAAAZgAFhBoQgfgJgPgfQgGgOgEgSQgHgNgGgSIAAgQIAEgMIAHgUIADgOIAJgPQACgFAEgEQAPgPAfAJQAgAIAOAfQAOAWAHAQQACAKAAAKIgEAQQgKAogUAWIgEAEIgEADQgGAMgKADIgRgCgAFVhNQgIACgEAFIgDAHIgHALIgBANIgGAOIgEAKIAAAPQAEAKAFAJIABABQACARAEANQADANAIAIQAHAJALAEIAMAEIAEgEQACgDABgHIACgCIACgCQAGgIAFgJQAHgNAGgSIAEgKIAAgNIgFgMIgHgLIgDgPQgFgNgHgJQgHgIgLgFQgJgDgGAAIgDAAgAgPgMIAAgqIAiAAIAAAqg");
	this.shape_27.setTransform(363.675,489.65);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#333333").s().p("AmYBWQgSgcAAg6QAAg5ATgbQASgdAnAAQAnAAASAdQASAcAAA4QAAA6gSAcQgTAcgmAAQgnAAgTgcgAl1hSQgJAFgMAoQgCASAAATQAAAXACAPQABAQAGAMQAEAMAJAFQAJAHAPAAQAOAAAJgHQAJgFAFgMQAFgLACgRQABgQAAgWQAAgWgBgQQgCgQgFgLQgGgMgIgFQgJgHgOAAQgOAAgJAHgABvBtIAAgWIAtAAIAAiSIgtAAIAAgUIAUgBQAWgIAEgFQAEgHABgJIAXAAIAADEIAsAAIAAAWgAgOBtIAAgpIAiAAIAAApgAjoBtIAAgeIAfgbQAQgNANgNQAcgbAKgQQALgQAAgSQgXglgUAAQgNAAgPAGQgQAEgPAJIgBgeQAKgFASgEQARgEAQgBQAiAAATAQQATAQAAAcQAAANgDALQgEAKgGAKQgFAJgIAIIgTATQgPAQgRAOIgfAbIB1AAIAAAZgAFgBdQgXgRgLggQgFgQgDgTQgLgJgKgNIAAgSIAIgKQAKgNACgFIADgNIANgMIAFgCQAKgBAYAQQAYARAKAiIAbAfIACAVIgJAMQgTAdgcARIgDAAIgDAAQACAJgCACIgNgIgAFThKIgLAIIgCANQgCAEgJALIgIAHIAAAQIASAPIABAAQABASADAQQADAOAFALQAGALAIAJIAJAIIgBgDIgFgGIABABIACABQAJgGAIgIQANgJAMgNIAJgIIAAgRIgKgIIgKgIIgDgQQgDgPgFgKQgGgMgIgKIgOgKQgFgEgDABIgCgBIgBAAgAgOgMIAAgqIAiAAIAAAqg");
	this.shape_28.setTransform(363.575,489.65);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#333333").s().p("Al2BWQgSgcAAg6QAAg5ATgbQASgdAnAAQAnAAASAdQASAcAAA4QAAA6gSAcQgTAcgmAAQgnAAgTgcgAlThSQgJAFgMAoQgCASAAATQAAAXACAPQABAQAGAMQAEAMAJAFQAJAHAPAAQAOAAAJgHQAJgFAFgMQAFgLACgRQABgQAAgWQAAgWgBgQQgCgQgFgLQgGgMgIgFQgJgHgOAAQgOAAgJAHgACRBtIAAgWIAtAAIAAiSIgtAAIAAgUIAUgBQAWgIAEgFQAEgHABgJIAXAAIAADEIAsAAIAAAWgAATBtIAAgpIAjAAIAAApgAjGBtIAAgeIAfgbQAQgNANgNQAcgbAKgQQALgQAAgSQgXglgUAAQgNAAgPAGQgQAEgPAJIgBgeQAKgFASgEQARgEAQgBQAiAAATAQQATAQAAAcQAAANgDALQgEAKgGAKQgFAJgIAIIgTATQgPAQgRAOIgfAbIB1AAIAAAZgAGEBfIADgCIACAEIgFgCgAF8BcIgCgDIAKAGIgGACIgCgFgAGEBfIAAAAgAATgMIAAgqIAjAAIAAAqg");
	this.shape_29.setTransform(360.175,489.65);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#333333").s().p("Ak1BWQgSgcAAg6QAAg5ASgbQATgdAmAAQAoAAASAdQASAcAAA4QAAA6gSAcQgTAcgnAAQgmAAgTgcgAkShSQgKAFgLAoQgCASAAATQAAAXACAPQABAQAFAMQAFAMAJAFQAJAHAOAAQAOAAAKgHQAIgFAGgMQAEgLACgRQACgQAAgWQAAgWgCgQQgCgQgEgLQgGgMgIgFQgKgHgOAAQgOAAgIAHgADSBtIAAgWIAtAAIAAiSIgtAAIAAgUIATgBQAXgIAEgFQAEgHAAgJIAXAAIAADEIAtAAIAAAWgABUBtIAAgpIAjAAIAAApgAiFBtIAAgeIAfgbQAPgNANgNQAdgbAKgQQALgQAAgSQgXglgUAAQgNAAgPAGQgQAEgPAJIgCgeQALgFARgEQASgEAQgBQAhAAAUAQQARAQAAAcQAAANgCALQgDAKgGAKQgFAJgJAIIgSATQgQAQgRAOIgeAbIBzAAIAAAZgABUgMIAAgqIAjAAIAAAqg");
	this.shape_30.setTransform(353.7,489.65);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#333333").s().p("AmUBWQgSgcAAg6QAAg5ASgbQASgdAnAAQAoAAASAdQASAcAAA4QAAA6gTAcQgSAcgnAAQgnAAgSgcgAlxhSQgKAFgFAMQgFAKgCASQgBASAAATQAAAXABAPQACAQAFAMQAFAMAJAFQAJAHAOAAQAOAAAJgHQAJgFAFgMQAFgLACgRQACgQAAgWQAAgWgCgQQgCgQgFgLQgFgMgJgFQgJgHgOAAQgOAAgIAHgAExBtIAAgWIAtAAIAAiSIgtAAIAAgUIAUgBQAKgCAGgCQAGgEAEgFQAEgHABgJIAXAAIAADEIAsAAIAAAWgAByBtIAAgWIAuAAIAAiSIguAAIAAgUIAUgBQALgCAFgCQAHgEAEgFQAEgHAAgJIAXAAIAADEIAtAAIAAAWgAgLBtIAAgpIAiAAIAAApgAjkBtIAAgeIAfgbQAPgNANgNQAdgbAKgQQAKgQAAgSQAAgRgLgKQgLgJgUgBQgNAAgQAGQgPAEgPAJIgCAAIAAgeQALgFARgEQARgEARgBQAhAAATAQQATAQAAAcQAAANgDALQgDAKgGAKQgGAJgIAIIgSATQgQAQgRAOIgfAbIB1AAIAAAZgAgLgMIAAgqIAiAAIAAAqg");
	this.shape_31.setTransform(363.225,489.65);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#333333").s().p("AmVBWQgSgcAAg6QAAg5ATgbQASgdAnAAQAnAAASAdQASAcAAA4QAAA6gSAcQgTAcgmAAQgnAAgTgcgAlyhSQgJAFgMAoQgCASAAATQAAAXACAPQABAQAGAMQAEAMAJAFQAJAHAPAAQAOAAAJgHQAJgFAFgMQAFgLACgRQABgQAAgWQAAgWgBgQQgCgQgFgLQgGgMgIgFQgJgHgOAAQgOAAgJAHgAFDBtIgUgBIgBgHIAAgPIAHgDIACAAIAUADIASABIABgDIADgJIADgKIACgJIABgNIgBgNIgCgKIgCgJIgEgKIgCgFIAAgPIACgGIAGgTIABgLIgIgDIgHgDIgIgBIgIgBIgJAAIgFAAIgEgKIgCgGIAHACIAGgDIAKgGIAFgCQAHgDAEgFIACgCQAEgFADgGIAKAAIANAAIACAKIAEATIADAZIAAAXQAAAQgCAQIgFAdIAAADIADAPIADANIABAPIABAAIATAFIASADIgBADIgCAUIgDABIgdACIgfABIgjgBgAByBtIAAgWIAtAAIAAiSIgtAAIAAgUIAUgBQAWgIAEgFQAEgHABgJIAXAAIAADEIAsAAIAAAWIh2AAgAgLBtIAAgpIAiAAIAAApIgiAAgAjlBtIAAgeIAfgbQAQgNANgNQAcgbAKgQQALgQAAgSQgXglgUAAQgNAAgPAGQgQAEgPAJQgBgOAAgQQAKgFASgEQARgEAQgBQAiAAATAQQATAQAAAcQAAANgDALQgEAKgGAKQgFAJgIAIIgTATQgPAQgRAOIgfAbIB1AAIAAAZIiUAAgAgLgMIAAgqIAiAAIAAAqIgiAAg");
	this.shape_32.setTransform(363.275,489.65);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#333333").s().p("AmVBWQgSgcAAg6QAAg5ASgbQATgdAmAAQAoAAASAdQASAcAAA4QAAA6gSAcQgTAcgnAAQgmAAgTgcgAlyhSQgKAFgLAoQgCASAAATQAAAXACAPQABAQAFAMQAFAMAJAFQAJAHAOAAQAOAAAKgHQAIgFAGgMQAEgLACgRQACgQAAgWQAAgWgCgQQgCgQgEgLQgGgMgIgFQgKgHgOAAQgOAAgIAHgAFCBtIgUgCIgEgHIAAgOIAHgGIABAAIAXAGIAUABIABgCIAHgHQAEgGABgFIAEgKIABgOQAAgIgBgHQgBgFgDgFQgCgEgDgEIgHgJIgEgDIAAgSIADgEQAHgHAFgLIADgKIgGgGQgCgCgEgDIgIgDIgJgCIgLAAIgEAAIgJgHIgBgBIAEgEQAFgDADgFIAGgCQAGgDAGgFIACgCIAKgKIAKAAIAOAAIAEAKIAHAQQAEALACAMQABALABANQgBAQgEAPQgEAOgGANIAAADIAGAMIAFANIAEAPIAAAAQAJADAHAFIANAJIgBACIgDAUIgEABIgcAFQgPABgQAAQgSAAgRgBgAByBtIAAgWIAtAAIAAiSIgtAAIAAgUIATgBQAXgIAEgFQAEgHAAgJIAXAAIAADEIAtAAIAAAWIh2AAgAgLBtIAAgpIAiAAIAAApIgiAAgAjlBtIAAgeIAfgbQAPgNANgNQAdgbAKgQQALgQAAgSQgXglgUAAQgNAAgPAGQgQAEgPAJQgBgOgBgQQALgFARgEQASgEAQgBQAhAAAUAQQASAQAAAcQAAANgCALQgEAKgGAKQgFAJgJAIIgSATQgQAQgRAOIgeAbIB0AAIAAAZIiTAAgAgLgMIAAgqIAiAAIAAAqIgiAAgAE2hLIAAgBIAAABgAEzhPIADADIAAAAIgDgDgAE2hMIAAAAg");
	this.shape_33.setTransform(363.3,489.65);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#333333").s().p("AmVBWQgTgcABg6QAAg5ASgbQASgdAnAAQAnAAASAdQATAcgBA4QAAA6gSAcQgTAcgmAAQgnAAgSgcgAlzhSQgJAFgMAoQgCASABATQgBAXACAPQACAQAFAMQAFAMAIAFQAJAHAPAAQAOAAAJgHQAJgFAFgMQAFgLACgRQABgQAAgWQAAgWgBgQQgCgQgFgLQgFgMgJgFQgJgHgOAAQgOAAgJAHgAFABtIgUgCIgEgHIAAgOIAEgIIACAAQALAEANADIAWADIADgCIAJgGQAFgFAEgFQADgGABgFQACgIAAgIQAAgJgCgHQgCgGgDgEQgDgFgEgDIgLgHIgGgCIAAgUIAEgDQAMgGAGgJIAFgKQAAgEgDgFQgCgFgEgCIgIgGQgFgCgFAAIgMgBIgGAAIgLgEIgGgCIgDAGIAAAAIADgGQADgGADgFIAGgDIAOgHIABgCIAOgIIAKAAIAOAAIAGAIQAGAGAFAIQAGAKACAMQADAKAAANQAAARgGAPQgGAOgKAJIAAAEIAJAKQAFAFADAHQADAHACAJIAAAAQAJAEAFAHIAJAOIgBABIgGAUIgDABQgNAFgPADQgPACgRAAQgRAAgSgCgABxBtIAAgWIAtAAIAAiSIgtAAIAAgUIAUgBQAXgIADgFQAFgHAAgJIAXAAIAADEIAsAAIAAAWIh2AAgAgMBtIAAgpIAiAAIAAApIgiAAgAjmBtIAAgeIAggbQAPgNANgNQAcgbALgQQAKgQAAgSQgWglgVAAQgNAAgPAGQgPAEgPAJQgCgOAAgQQALgFARgEQARgEARgBQAhAAATAQQATAQAAAcQAAANgDALQgEAKgGAKQgFAJgIAIIgSATQgQAQgRAOIgfAbIB1AAIAAAZIiUAAgAgMgMIAAgqIAiAAIAAAqIgiAAg");
	this.shape_34.setTransform(363.35,489.65);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#333333").s().p("AmWBWQgSgcAAg6QAAg5ATgbQASgdAnAAQAnAAASAdQASAcAAA4QAAA6gSAcQgTAcgmAAQgnAAgTgcgAlzhSQgJAFgMAoQgCASAAATQAAAXACAPQABAQAGAMQAEAMAJAFQAJAHAPAAQAOAAAJgHQAJgFAFgMQAFgLACgRQABgQAAgWQAAgWgBgQQgCgQgFgLQgGgMgIgFQgJgHgOAAQgOAAgJAHgAE/BtIgUgDIgGgGIAAgOIADgLIABAAQAMAFAOAEQANADALABIADgBQAGgCAHgEQAHgEAFgGQAEgFACgGQADgIAAgKQAAgJgDgHQgCgHgFgEQgEgFgGgDIgOgFIgJgCIAAgUIAHgCQAPgEAJgJQADgEACgGQACgFgCgHQgBgGgEgEQgDgEgFgCQgGgDgGgBIgNgBIgFAAQgIgBgIAAIgIAAIgIAHIgBAAIADgHIADgOIAHgEIAPgGIACgCIARgGIAKAAIAOAAIAJAGQAIAFAHAIQAHAJADALQAEAKAAANQAAARgIAPQgJAOgMAHIAAADIALAJQAGAFAEAFQAFAIADAIIAAAAQAHAHADAKQAEAJABAHIgBADQgDAKgFAJIgDACQgMAHgPACQgPAEgRAAQgSAAgRgDgABxBtIAAgWIAtAAIAAiSIgtAAIAAgUIAUgBQAWgIAEgFQAEgHABgJIAXAAIAADEIAsAAIAAAWIh2AAgAgMBtIAAgpIAiAAIAAApIgiAAgAjmBtIAAgeIAfgbQAQgNANgNQAcgbAKgQQALgQAAgSQgXglgUAAQgNAAgPAGQgQAEgPAJQgBgOAAgQQAKgFASgEQARgEAQgBQAiAAATAQQATAQAAAcQAAANgDALQgEAKgGAKQgFAJgIAIIgTATQgPAQgRAOIgfAbIB1AAIAAAZIiUAAgAgMgMIAAgqIAiAAIAAAqIgiAAg");
	this.shape_35.setTransform(363.375,489.65);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#333333").s().p("AmXBWQgSgcAAg6QAAg5ATgbQASgdAnAAQAnAAASAdQASAcAAA4QAAA6gSAcQgTAcgmAAQgnAAgTgcgAl0hSQgJAFgMAoQgCASAAATQAAAXACAPQABAQAGAMQAEAMAJAFQAJAHAPAAQAOAAAJgHQAJgFAFgMQAFgLACgRQABgQAAgWQAAgWgBgQQgCgQgFgLQgGgMgIgFQgJgHgOAAQgOAAgJAHgAE9BtIgUgEIgIgFIAAgOIACgOIABAAQAMAHAQAEQAOAEAMABIAEgBQAHgBAJgDQAJgDAFgHQAGgGADgGQACgIAAgLQAAgLgDgGQgDgIgGgFQgFgEgIgCQgHgDgKgBIgKgBIAAgVIAIgBQATgCAKgKQAFgDADgGQADgGgBgJQgBgHgDgFQgEgFgFgDQgGgDgHgBIgOgBIgFAAQgKgBgLADIgJABIgOAIIAAAAIABgIIACgRIAHgDIAQgGIACgCQALgDAJgBIAKgBIAPABIALAEQAKAEAIAGQAJAJAEAKQAFALAAANQAAARgKAOQgLAOgPAGIAAADQAGABAIAEQAHAEAFAHQAGAGAEAJQAGAIACANQABALgCAKIAAACQgEALgGAHIgDADQgMAJgPADQgPAEgRABQgSgBgRgDgABwBtIAAgWIAtAAIAAiSIgtAAIAAgUIAUgBQAWgIAEgFQAEgHABgJIAXAAIAADEIAsAAIAAAWIh2AAgAgNBtIAAgpIAiAAIAAApIgiAAgAjnBtIAAgeIAfgbQAQgNANgNQAcgbAKgQQALgQAAgSQgXglgUAAQgNAAgPAGQgQAEgPAJQgBgOAAgQQAKgFASgEQARgEAQgBQAiAAATAQQATAQAAAcQAAANgDALQgEAKgGAKQgFAJgIAIIgTATQgPAQgRAOIgfAbIB1AAIAAAZIiUAAgAgNgMIAAgqIAiAAIAAAqIgiAAg");
	this.shape_36.setTransform(363.4571,489.65);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#333333").s().p("AE5BtQgSgEgLgFIAAgfIACAAQANAIARAGQARAFAPAAQAJAAALgDQAKgDAHgGQAGgGAEgIQADgIAAgMQAAgLgEgIQgDgIgHgFQgHgEgJgBQgJgCgLAAIgNAAIAAgXIAKAAQAWgBANgIQAOgKAAgSQAAgIgEgGQgDgGgGgDQgGgEgIgCQgHgBgJgBQgOAAgPAGQgQAFgOAIIgBAAIAAgeQAKgFARgEQASgEAQgBQAQABAMADQAMACAKAHQALAGAFALQAFAJAAAOQAAASgMAOQgNANgSAEIAAACQAHABAJADQAKAFAGAEQAHAGAEAKQAFAJAAAQQAAAPgGAMQgFAMgKAJQgLALgPAEQgOAFgSABQgSAAgSgFgAmZBWQgSgcAAg6QAAg5ATgbQASgdAnAAQAnAAASAdQASAcAAA4QAAA6gSAcQgTAcgmAAQgnAAgTgcgAl2hSQgJAFgFAMQgFAKgCASQgCASAAATQAAAXACAPQABAQAGAMQAEAMAJAFQAJAHAPAAQAOAAAJgHQAJgFAFgMQAFgLACgRQABgQAAgWQAAgWgBgQQgCgQgFgLQgGgMgIgFQgJgHgOAAQgOAAgJAHgABuBtIAAgWIAtAAIAAiSIgtAAIAAgUIAUgBQAKgCAGgCQAGgEAEgFQAEgHABgJIAXAAIAADEIAsAAIAAAWgAgPBtIAAgpIAiAAIAAApgAjpBtIAAgeIAfgbQAQgNANgNQAcgbAKgQQALgQAAgSQAAgRgLgKQgMgJgUgBQgNAAgPAGQgQAEgPAJIgBAAIAAgeQAKgFASgEQARgEAQgBQAiAAATAQQATAQAAAcQAAANgDALQgEAKgGAKQgFAJgIAIIgTATQgPAQgRAOIgfAbIB1AAIAAAZgAgPgMIAAgqIAiAAIAAAqg");
	this.shape_37.setTransform(363.675,489.65);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#333333").s().p("AmZBWQgTgcABg6QAAg5ASgbQASgdAnAAQAnAAASAdQATAcgBA4QAAA6gSAcQgTAcgmAAQgnAAgSgcgAl3hSQgJAFgMAoQgCASABATQgBAXACAPQACAQAFAMQAFAMAIAFQAJAHAPAAQAOAAAJgHQAJgFAFgMQAFgLACgRQABgQAAgWQAAgWgBgQQgCgQgFgLQgFgMgJgFQgJgHgOAAQgOAAgJAHgAFPBuIgFgBIgMgCIgPgFIgBgDIAAgaIACAAQAKAFANACQANACAMgCIABAAQAGAAAHgCQAIgDADgEQAEgGADgGQABgGgBgKQgBgJgFgGQgEgHgGgDQgHgEgIgBIgTgBIgMAAIAAgCIAAgTIAIgCQAHgBAHgDQAJgCAGgGQAMgIACgQQAAgIgCgFQgCgFgEgEQgFgEgFgBIgMgDQgKgBgLADQgLACgKAFIgBAAIADgbQAHgFANgEIAEgCQAMgDALgCIAHAAQAOAAANACIAAAAQAKAEAIAGQAIAJAEAKQAFAKAAAMQgBARgJAOQgLANgOAGIAAACQAGACAHAEIAHAEIAHAEQAGAFAFAIQAEAFADAJIAAAHQgBANgDAKIgBACQgGAKgKAHIgLAGQgFAFgHAEQgLAGgPADQgKACgKAAIgEAAgABtBtIAAgWIAtAAIAAiBIAAgRIgDAAIgqAAIAAgUIAUgBQAXgIADgFQAFgHAAgJIAXAAIAAAmIAAAdIAAByIgVgCIAAAQIAVgCIAAADIAsAAIAAAWIh2AAgAgQBtIAAgpIAiAAIAAApIgiAAgAjqBtIAAgeIAggbQAPgNANgNQAcgbALgQQAKgQAAgSQgWglgVAAQgNAAgPAGQgPAEgPAJQgCgOAAgQQALgFARgEQARgEARgBQAhAAATAQQATAQAAAcQAAANgDALQgEAKgGAKQgFAJgIAIIgSATQgQAQgRAOIgfAbIB1AAIAAAZIiUAAgAgQgMIAAgqIAiAAIAAAqIgiAAg");
	this.shape_38.setTransform(363.75,489.65);

	this.shape_39 = new cjs.Shape();
	this.shape_39.graphics.f("#333333").s().p("AmaBWQgSgcAAg6QAAg5ASgbQASgdAnAAQAoAAASAdQASAcAAA4QAAA6gTAcQgSAcgnAAQgnAAgSgcgAl3hSQgKAFgMAoQgBASAAATQAAAXABAPQACAQAFAMQAFAMAJAFQAJAHAOAAQAOAAAJgHQAJgFAFgMQAFgLACgRQACgQAAgWQAAgWgCgQQgCgQgFgLQgFgMgJgFQgJgHgOAAQgOAAgIAHgAFaBtIgLgCIgPgDIgBgDIAAgXIABAAQAIABAKgBQAKgCAJgEIABAAQADAAADgCQAEgCACgEQACgEAAgEIgDgMQgCgGgFgFQgFgFgGgCQgGgDgHgCIgSAAIgLAAIgBgBIAAgUIAGgBQAGgDAFgEQAIgCAFgGQALgIADgOQABgGgBgEQgCgGgCgCQgDgFgDgCIgHgDQgGgDgHAAQgHAAgGADIAAAAIAFgZQAHgFALgEIADgCIAVgIIAHAAQANAAAMABIAAABQAHAFAGAGQAHAKADAJQADALAAAMQAAAQgIANQgHANgLAIIAAADIAKAHIAFAEIAGADQAHAEAGAFQAEAFADAGIAAAGQAAANgCAKIgBABQgHAHgKAGIgLAFIgJAKQgJAIgLAFQgJAFgIACIgGgBgABsBtIAAgWIAuAAIAAiSIguAAIAAgUIAUgBQAXgIAEgFQAEgHAAgJIAXAAIAABIIgBAAIABAFIAAB3IAtAAIAAAWIh3AAgAgRBtIAAgpIAiAAIAAApIgiAAgAjqBtIAAgeIAfgbQAPgNANgNQAdgbAKgQQAKgQAAgSQgWglgUAAQgNAAgQAGQgPAEgPAJQgCgOAAgQQALgFARgEQARgEARgBQAhAAATAQQATAQAAAcQAAANgDALQgDAKgGAKQgGAJgIAIIgSATQgQAQgRAOIgfAbIB1AAIAAAZIiTAAgAgRgMIAAgqIAiAAIAAAqIgiAAg");
	this.shape_39.setTransform(363.825,489.65);

	this.shape_40 = new cjs.Shape();
	this.shape_40.graphics.f("#333333").s().p("AmbBWQgSgcAAg6QAAg5ASgbQASgdAnAAQAoAAASAdQASAcAAA4QAAA6gTAcQgSAcgnAAQgnAAgSgcgAl4hSQgKAFgMAoQgBASAAATQAAAXABAPQACAQAFAMQAFAMAJAFQAJAHAOAAQAOAAAJgHQAJgFAFgMQAFgLACgRQACgQAAgWQAAgWgCgQQgCgQgFgLQgFgMgJgFQgJgHgOAAQgOAAgIAHgAFqBtIgKgBIgOgCIgCgCIAAgVIABgBIAMgHQAHgEAGgIIABgBIgBgDIgBgFIgHgJQgEgFgFgDQgEgCgGgCIgNgDIgPgBIgKAAIgDAAIAAgHIAAgLIAEgDIAIgIIAHgFIAEgDQAJgJAEgLIACgJQAAgFgBgDIgCgGIgDgEQgCgFgCgCIgEgEIAAAAIAHgWIAPgJIAEgCIARgLIAHAAQAMAAALACIABAAQAFAGADAIQAFAJACALQACAJAAALQAAAQgFANQgFAOgHAKIAAABIAGAKIAEAEIAFACQAIACAGAFQAFACAEAEIAAAGQAAAMgCAJIgBABIgSAJIgLADIgGALQgGAKgHAIIgMALIgFAAgABrBtIAAgWIAuAAIAAiSIguAAIAAgUIAUgBQAXgIAEgFQAEgHAAgJIAXAAIAADEIAtAAIAAAWIh3AAgAgSBtIAAgpIAiAAIAAApIgiAAgAjrBtIAAgeIAfgbQAPgNANgNQAdgbAKgQQAKgQAAgSQgWglgUAAQgNAAgQAGQgPAEgPAJQgCgOAAgQQALgFARgEQARgEARgBQAhAAATAQQATAQAAAcQAAANgDALQgDAKgGAKQgGAJgIAIIgSATQgQAQgRAOIgfAbIB1AAIAAAZIiTAAgAgSgMIAAgqIAiAAIAAAqIgiAAg");
	this.shape_40.setTransform(363.925,489.65);

	this.shape_41 = new cjs.Shape();
	this.shape_41.graphics.f("#333333").s().p("AmcBWQgSgcAAg6QAAg5ASgbQATgdAmAAQAoAAASAdQASAcAAA4QAAA6gSAcQgTAcgnAAQgmAAgTgcgAl5hSQgKAFgLAoQgCASAAATQAAAXACAPQABAQAFAMQAFAMAJAFQAJAHAOAAQAOAAAJgHQAJgFAGgMQAEgLACgRQACgQAAgWQAAgWgCgQQgCgQgEgLQgGgMgJgFQgJgHgOAAQgOAAgIAHgAF7BtIgKgBIgNgBIgCAAIAAgTIAAgBIAGgOIAHgSIgGAAIgHgCIgEgCIgKgFIgMgDIgKgDIgMgBIgNgBIgJAAIgEAAIAAgQIACgFIAEgIIAqAZIgJgPIAAgDIAYgnIAAgMIgEgHIgMAIIgNAEIABgDIABgGIABgFIAFgLIAFgKIgBAAIALgTIAMgJIADgDIAPgNIAGAAIAXABIAAAAIAEAQQADAKABALIABAUQgBAOgCANIgGAYIAAADIADANIACADIAFABIAPADIAKADIAAAGIgBAUIgBABIgTADIgLADIgDAMIgHAVIgFARIgFAAgABrBtIAAgWIAtAAIAAiSIgtAAIAAgUIATgBQAXgIAEgFQAEgHAAgJIAXAAIAADEIAtAAIAAAWIh2AAgAgSBtIAAgpIAiAAIAAApIgiAAgAjsBtIAAgeIAfgbQAPgNANgNQAdgbAKgQQALgQAAgSQgXglgUAAQgNAAgPAGQgQAEgPAJQgBgOgBgQQALgFARgEQASgEAQgBQAhAAAUAQQASAQAAAcQAAANgCALQgEAKgGAKQgFAJgJAIIgSATQgQAQgRAOIgeAbIB0AAIAAAZIiTAAgAgSgMIAAgqIAiAAIAAAqIgiAAg");
	this.shape_41.setTransform(364,489.65);

	this.shape_42 = new cjs.Shape();
	this.shape_42.graphics.f("#333333").s().p("AmdBWQgSgcAAg6QAAg5ATgbQASgdAnAAQAnAAASAdQASAcAAA4QAAA6gSAcQgTAcgmAAQgnAAgTgcgAl6hSQgJAFgFAMQgFAKgCASQgCASAAATQAAAXACAPQABAQAGAMQAEAMAJAFQAJAHAPAAQAOAAAJgHQAJgFAFgMQAFgLACgRQABgQAAgWQAAgWgBgQQgCgQgFgLQgGgMgIgFQgJgHgOAAQgOAAgJAHgAFzBtIAAg+IhoAAIAAghIBqh6IAbAAIAACEIAgAAIAAAXIggAAIAAA+gAEfAYIBUAAIAAhhgABqBtIAAgWIAtAAIAAiSIgtAAIAAgUIAUgBQAKgCAGgCQAGgEAEgFQAEgHABgJIAXAAIAADEIAsAAIAAAWgAgTBtIAAgpIAiAAIAAApgAjtBtIAAgeIAfgbQAQgNANgNQAcgbAKgQQALgQAAgSQAAgRgLgKQgMgJgUgBQgNAAgPAGQgQAEgPAJIgBAAIAAgeQAKgFASgEQARgEAQgBQAiAAATAQQATAQAAAcQAAANgDALQgEAKgGAKQgFAJgIAIIgTATQgPAQgRAOIgfAbIB1AAIAAAZgAgTgMIAAgqIAiAAIAAAqg");
	this.shape_42.setTransform(364.075,489.65);

	this.shape_43 = new cjs.Shape();
	this.shape_43.graphics.f("#333333").s().p("AmbBWQgTgcABg6QAAg5ASgbQASgdAnAAQAnAAASAdQATAcgBA4QAAA6gSAcQgTAcgmAAQgnAAgSgcgAl5hSQgJAFgMAoQgCASABATQgBAXACAPQACAQAFAMQAFAMAIAFQAJAHAPAAQAOAAAJgHQAJgFAFgMQAFgLACgRQABgQABgWQgBgWgBgQQgCgQgFgLQgFgMgJgFQgJgHgOAAQgOAAgJAHgABrBtIAAgWIAtAAIAAiSIgtAAIAAgUIAUgBQAXgIADgFQAFgHAAgJIAXAAIAADEIAsAAIAAAWgAgSBtIAAgpIAiAAIAAApgAjsBtIAAgeIAggbQAPgNANgNQAcgbALgQQAKgQAAgSQgWglgVAAQgNAAgPAGQgPAEgPAJIgCgeQALgFARgEQARgEARgBQAhAAATAQQATAQAAAcQAAANgDALQgEAKgGAKQgFAJgIAIIgSATQgQAQgRAOIgfAbIB1AAIAAAZgAF6BLIAEgMIABgKIAAgFIgKAEIgTAEIgWAEIgYABIgagBIgHAAIgDgMIAAgXIABAAIAhgXIAMgHIALgKIADgFIgBgFIAAgDIARgrIAJgEIABgCIAEgKIAHABIALgDIAAAVIgLgMIgMAFIgCAJIgEAKIgDAJIgFALIgIAMIgDAEIAAAAIABAFIABAGIAAAEIgDAGIgDAIIgFAGIgGAGIgIAFQgFADgRAEIAAABIAHAFIAOACIAOABIAPgBIAMgEQAFgBAFgDIAIgGIAHgGIADgEIAAgBIgDgHIgHgHIgCgCIgCgDIAAgZIAUgYIATAzIAOAAIAOADIAAAAIgHATIgjAAIgDAHIAAArIADAGIACAFIgCAAIgLAAIgCABIADgIgAgSgMIAAgqIAiAAIAAAqg");
	this.shape_43.setTransform(363.95,489.65);

	this.shape_44 = new cjs.Shape();
	this.shape_44.graphics.f("#333333").s().p("AmaBWQgTgcABg6QAAg5ASgbQASgdAnAAQAnAAASAdQATAcgBA4QAAA6gSAcQgTAcgmAAQgnAAgSgcgAl4hSQgJAFgMAoQgCASABATQgBAXACAPQACAQAFAMQAFAMAIAFQAJAHAPAAQAOAAAJgHQAJgFAFgMQAFgLACgRQABgQAAgWQAAgWgBgQQgCgQgFgLQgFgMgJgFQgJgHgOAAQgOAAgJAHgABsBtIAAgWIAtAAIAAiSIgtAAIAAgUIAUgBQAXgIADgFQAFgHAAgJIAXAAIAADEIAsAAIAAAWgAgRBtIAAgpIAiAAIAAApgAjrBtIAAgeIAggbQAPgNANgNQAcgbALgQQAKgQAAgSQgWglgVAAQgNAAgPAGQgPAEgPAJIgCgeQALgFARgEQARgEARgBQAhAAATAQQATAQAAAcQAAANgDALQgEAKgGAKQgFAJgIAIIgSATQgQAQgRAOIgfAbIB1AAIAAAZgAEjBIIgIgBIgHgJIAAgaIABAAQAegHALgFIANgHQAGgFAGgFIAGgHIAAABQABAEgCAGQgBAGgCAFIgGAIQgEAEgFADIgKAEQgJACgXAAIgBAAIAAAAIAGAMIARAEQAJABALAAQAKAAAJgDQAIgCAHgDIAHgFIAEAEIAEAEIgBAAQABAAAAAAQAAAAAAAAQAAAAAAABQAAAAgBAAIABABIAGgEIAIgDQAAgBABAAQAAAAAAAAQABAAAAAAQAAAAAAABIgBAAIgJAGQgHAFgLAEQgKAFgLABQgNADgOAAQgOAAgOgCgAFrgEIgFgDIgEgCIAAAAIAAghIAFgCIgBgFIgDgJIgDgFIAHgIIAAgBIAtAsIAQAAIAJAKIAAAAIgOAOIgnAAIgEAEIgJgEgAgRgMIAAgqIAiAAIAAAqgAFfhAIABABIgBAAIAAgBgAFgg/IAAAAg");
	this.shape_44.setTransform(363.85,489.65);

	this.shape_45 = new cjs.Shape();
	this.shape_45.graphics.f("#333333").s().p("AmaBWQgSgcAAg6QAAg5ASgbQATgdAmAAQAoAAASAdQASAcAAA4QAAA6gSAcQgTAcgnAAQgmAAgTgcgAl3hSQgKAFgLAoQgCASAAATQAAAXACAPQABAQAFAMQAFAMAJAFQAJAHAOAAQAOAAAKgHQAIgFAGgMQAEgLACgRQACgQAAgWQAAgWgCgQQgCgQgEgLQgGgMgIgFQgKgHgOAAQgOAAgIAHgABtBtIAAgWIAtAAIAAiSIgtAAIAAgUIATgBQAXgIAEgFQAEgHAAgJIAXAAIAADEIAtAAIAAAWgAgQBtIAAgpIAiAAIAAApgAjqBtIAAgeIAfgbQAPgNANgNQAdgbAKgQQALgQAAgSQgXglgUAAQgNAAgPAGQgQAEgPAJIgCgeQALgFARgEQASgEAQgBQAhAAAUAQQASAQAAAcQAAANgCALQgEAKgGAKQgFAJgJAIIgSATQgQAQgRAOIgeAbIB0AAIAAAZgAErBVIgJgCQgGgDgEgGIAAgbIABAAQAiACAMgEQAJgCAIgEQAHgDAGgHIAEgEIAEgHIABgBQADgHACgJIABgJIAFACQAHADAGADIABACQAFAEACAJQACAHgCALIgHgCIgJAAIgDgCQgEgCgGAAIgBAAIgEgBIgCAJQgDAFgEAFQgGAGgGADIgOADQgLABgdgGIgBAAIAAABIADARIAUAFQANADAMAAQANAAALgEQALgDAIgGQAIgGAEgIQAGgJABgIIAAgBIAEADQAFADAAAHIgBAFIgIAKQgHAIgKAFQgKAHgNADQgNADgQAAQgQAAgOgCgAFngLIgEgBIgDgBIgIgBIAAgcIgEgBIgHACIAFgMIAAgfIBEAdIAQAAIAHAQIgCAAIgVAJIgrAAIAGAGQADAFAAAGIAAAFIgNgDgAgQgMIAAgqIAiAAIAAAqg");
	this.shape_45.setTransform(363.8,489.65);

	this.shape_46 = new cjs.Shape();
	this.shape_46.graphics.f("#333333").s().p("AmZBWQgSgcAAg6QAAg5ASgbQASgdAnAAQAoAAASAdQASAcAAA4QAAA6gTAcQgSAcgnAAQgnAAgSgcgAl2hSQgKAFgMAoQgBASAAATQAAAXABAPQACAQAFAMQAFAMAJAFQAJAHAOAAQAOAAAJgHQAJgFAFgMQAFgLACgRQACgQAAgWQAAgWgCgQQgCgQgFgLQgFgMgJgFQgJgHgOAAQgOAAgIAHgABtBtIAAgWIAuAAIAAiSIguAAIAAgUIAUgBQAXgIAEgFQAEgHAAgJIAXAAIAADEIAtAAIAAAWgAgQBtIAAgpIAiAAIAAApgAjpBtIAAgeIAfgbQAPgNANgNQAdgbAKgQQAKgQAAgSQgWglgUAAQgNAAgQAGQgPAEgPAJIgCgeQALgFARgEQARgEARgBQAhAAATAQQATAQAAAcQAAANgDALQgDAKgGAKQgGAJgIAIIgSATQgQAQgRAOIgfAbIB1AAIAAAZgAEzBiIgJgDQgIgDgGgEIAAgdIABAAQAoAJANgCQAKgBAJgDQAIgDAHgHQAGgGADgHIABgCIgDAKQgDAIgFAFQgHAHgIADQgIACgJAAQgNABglgMIgCAAIAAABIACAYQAKAEAOADQAPADAPAAQAQAAANgFQAMgEAKgIQAJgIAFgLQAFgLABgNIAAgMQAEAHAAAMIgBAJIgGAMQgGAMgKAHQgLAJgNAEQgOAFgRgBQgRAAgQgCgAGdAWQgFgJgKgEQgGgDgGgBIgBAAIgFgCIgLgCIgKgBIgCAAIgHAAIgKAAIAAgUIAGAAIAIACQAOABALADQAJADAHAEIADACQAIAGAFAKQACAGABAHIgBgCgAgQgMIAAgqIAiAAIAAAqgAE+gjIAAg9IBZAPIASAAIADAUIgCAAIgdAFIguAAIgLACIAAAiIgGgBIgFAAIgOADg");
	this.shape_46.setTransform(363.725,489.65);

	this.shape_47 = new cjs.Shape();
	this.shape_47.graphics.f("#333333").s().p("AE6BuQgQgEgMgFIAAgfIACAAQAMAHAQAGQARAFAPAAQAKAAAKgCQAKgEAHgHQAHgHADgIQADgJAAgMQAAgKgDgJQgEgHgHgFQgHgGgLgCQgLgBgOAAQgMAAgNABIgUADIAAhvICDAAIAAAaIhnAAIAAA5IANgBIAMAAQARAAANADQANAEAMAHQALAIAHAMQAGAMABATQgBAQgFAOQgGAOgKAJQgKAKgOAGQgPAGgTAAQgSAAgRgEgAmZBWQgTgcABg6QAAg5ASgbQASgdAnAAQAnAAASAdQATAcgBA4QAAA6gSAcQgTAcgmAAQgnAAgSgcgAl3hSQgJAFgFAMQgFAKgCASQgCASABATQgBAXACAPQACAQAFAMQAFAMAIAFQAJAHAPAAQAOAAAJgHQAJgFAFgMQAFgLACgRQABgQAAgWQAAgWgBgQQgCgQgFgLQgFgMgJgFQgJgHgOAAQgOAAgJAHgABtBtIAAgWIAtAAIAAiSIgtAAIAAgUIAUgBQAKgCAGgCQAGgEAEgFQAFgHAAgJIAXAAIAADEIAsAAIAAAWgAgQBtIAAgpIAiAAIAAApgAjqBtIAAgeIAggbQAPgNANgNQAcgbALgQQAKgQAAgSQAAgRgLgKQgLgJgVgBQgNAAgPAGQgPAEgPAJIgCAAIAAgeQALgFARgEQARgEARgBQAhAAATAQQATAQAAAcQAAANgDALQgEAKgGAKQgFAJgIAIIgSATQgQAQgRAOIgfAbIB1AAIAAAZgAgQgMIAAgqIAiAAIAAAqg");
	this.shape_47.setTransform(363.75,489.65);

	this.shape_48 = new cjs.Shape();
	this.shape_48.graphics.f("#333333").s().p("AmaBWQgSgcAAg6QAAg5ASgbQATgdAmAAQAoAAASAdQASAcAAA4QAAA6gSAcQgTAcgnAAQgmAAgTgcgAl3hSQgKAFgLAoQgCASAAATQAAAXACAPQABAQAFAMQAFAMAJAFQAJAHAOAAQAOAAAKgHQAIgFAGgMQAEgLACgRQACgQAAgWQAAgWgCgQQgCgQgEgLQgGgMgIgFQgKgHgOAAQgOAAgIAHgAFIBtQgOgCgLgDIgDgYIAAgBIACAAQAIAFALAFQAJADAJAAIAFAAQAHAAAGgDQAIgDAFgGIADgHIAEgHQACgHgBgLQgBgJgDgHQgEgHgGgGIgGgEIgJgDQgKgDgLgBIgUgCIgQABIAAgPIAAgjIABgdIADgbIANgDIARgDIAVgCQAWgCAXAAIAPABIALAAIAGABIAAAUIAAABIgCAEIgGgBIgQAAQgbAAgZADIgbAGIgBAZIAGATIABAFIANgCIAHAAIAFAAIAUACIAKACQAIACAGADIAKAHQAHAFAEAGQAEAEADAGQADAIABAMIAAAEIABAHQAAAOgFANQgFAMgJAJQgJAJgMAHIgHACQgKADgMABIgKAAQgLAAgLgCgAgQBtIAAgpIAiAAIAAApIgiAAgAjqBtIAAgeIAfgbQAPgNANgNQAdgbAKgQQALgQAAgSQgXglgUAAQgNAAgPAGQgQAEgPAJQgBgOgBgQQALgFARgEQASgEAQgBQAhAAAUAQQASAQAAAcQAAANgCALQgEAKgGAKQgFAJgJAIIgSATQgQAQgRAOIgeAbIB0AAIAAAZIiTAAgAgQgMIAAgqIAiAAIAAAqIgiAAgACagpIAAgSIgGAAIgnAAIAAgUIATgBQAXgIAEgFQAEgHAAgJIAXAAIAAAmIAAAiIgcgEg");
	this.shape_48.setTransform(363.8,489.65);

	this.shape_49 = new cjs.Shape();
	this.shape_49.graphics.f("#333333").s().p("AmaBWQgTgcABg6QAAg5ASgbQASgdAnAAQAnAAASAdQATAcgBA4QAAA6gSAcQgTAcgmAAQgnAAgSgcgAl4hSQgJAFgMAoQgCASABATQgBAXACAPQACAQAFAMQAFAMAIAFQAJAHAPAAQAOAAAJgHQAJgFAFgMQAFgLACgRQABgQAAgWQAAgWgBgQQgCgQgFgLQgFgMgJgFQgJgHgOAAQgOAAgJAHgAFXBtQgNgBgJgCIgHgRIAAgBIABAAQAEAEAGADQAFABAGAAIADAAQAEAAAEgEQAEgDADgFIACgFIACgGIgBgQQgBgIgEgHQgDgGgEgEIgGgGIgHgCQgHgEgJgDIgPgFIgNgCIAAgMIAAggQABgPACgOQABgOADgNIAMgGIARgFIAVgFQAVgEAYABIAOAAIAMABIAEADIAAATIAAABIgCADIgHgBIgRgBQgbAAgYAHQgMAFgLAHIgDAZIAKALIADADIANgBIAHAAIAEAAQAMAAAJACIAKACQAHACAHAEIAJAHQAHAFAFAGQACAFACAFQAFAJAAAMIAAAEIAAAGQAAAMgEALQgEAMgIAJQgHAIgMAGIgGAEQgIACgLACIgRABIgJAAgABsBtIAAgWIAtAAIAAiSIgtAAIAAgUIAUgBQAXgIADgFQAFgHAAgJIAXAAIAADEIAsAAIAAABIgDAAIgKAAIADALIAKAAIAAAKIh2AAgAgRBtIAAgpIAiAAIAAApIgiAAgAjrBtIAAgeIAggbQAPgNANgNQAcgbALgQQAKgQAAgSQgWglgVAAQgNAAgPAGQgPAEgPAJQgCgOAAgQQALgFARgEQARgEARgBQAhAAATAQQATAQAAAcQAAANgDALQgEAKgGAKQgFAJgIAIIgSATQgQAQgRAOIgfAbIB1AAIAAAZIiUAAgAgRgMIAAgqIAiAAIAAAqIgiAAg");
	this.shape_49.setTransform(363.85,489.65);

	this.shape_50 = new cjs.Shape();
	this.shape_50.graphics.f("#333333").s().p("AmbBWQgSgcAAg6QAAg5ASgbQATgdAmAAQAoAAASAdQASAcAAA4QAAA6gSAcQgTAcgnAAQgmAAgTgcgAl4hSQgKAFgLAoQgCASAAATQAAAXACAPQABAQAFAMQAFAMAJAFQAJAHAOAAQAOAAAKgHQAIgFAGgMQAEgLACgRQACgQAAgWQAAgWgCgQQgCgQgEgLQgGgMgIgFQgKgHgOAAQgOAAgIAHgAFRBsIgGgHIACgBIACAAIABgEIACgHIAAgFIABgEIgDgOIgEgNIgHgKIgFgFIgEgDIgJgGIgDgDIgLgHIgJgEIAAgNIABgWIAAgFIADgdQADgPAEgNIALgHIAQgJIAUgHQAUgGAaABIAPAAIALACIACAEIAAAUIAAABIgDAAIgHgBIgRgBQgdAAgWAMQgMAHgJAKQgDALAAANIAOAEIAFABIANgBIAGAAIAFAAQALAAAKACIAKADIAMAGIAKAHQAGAGAFAGIAFAMQADAIABAMIAAAEIAAAFQgBALgDAKQgEAKgGAIQgHAJgJAGIgEACQgIAEgIADQgLADgMAAIgUgBgABsBtIAAgWIAtAAIAAiSIgtAAIAAgUIATgBQAXgIAEgFQAEgHAAgJIAXAAIAADEIAtAAIAAAWIh2AAgAgRBtIAAgpIAiAAIAAApIgiAAgAjrBtIAAgeIAfgbQAPgNANgNQAdgbAKgQQALgQAAgSQgXglgUAAQgNAAgPAGQgQAEgPAJQgBgOgBgQQALgFARgEQASgEAQgBQAhAAAUAQQASAQAAAcQAAANgCALQgEAKgGAKQgFAJgJAIIgSATQgQAQgRAOIgeAbIB0AAIAAAZIiTAAgAFLBkIgCgCIACADIAAgBgAFIBhIAAgBIAAAAIABACIgBgBgAgRgMIAAgqIAiAAIAAAqIgiAAg");
	this.shape_50.setTransform(363.9,489.65);

	this.shape_51 = new cjs.Shape();
	this.shape_51.graphics.f("#333333").s().p("AmbBWQgTgcABg6QAAg5ASgbQASgdAnAAQAnAAASAdQATAcgBA4QAAA6gSAcQgTAcgmAAQgnAAgSgcgAl5hSQgJAFgMAoQgCASABATQgBAXACAPQACAQAFAMQAFAMAIAFQAJAHAPAAQAOAAAJgHQAJgFAFgMQAFgLACgRQABgQABgWQgBgWgBgQQgCgQgFgLQgFgMgJgFQgJgHgOAAQgOAAgJAHgAFWBpQgFABgCAAIgGgBIABAAQgCgCgCgEIgEgGIgBgDIACAAQAJgCAIgFQARgJAJgSIAAgEIAAgIQgEgIgGgFIgCgCQgEgLgGgJQgGgIgGgEQgHgGgHgEIgVgKIgMADIgEADQACgPACgOQAEgPAGgMIAJgKQAHgHAJgFQAJgFAKgEQAUgHAaAAIAPAAIALACIACAHIAAAUIgBAAIgEgBIgHgBQgJgCgIAAQgeAAgVAQQgLAJgHANQgDALgBAOQAJgDAJgBIAHAAIAOgBIAGAAIADAAQAMgBAKADIAKADIAMAGQAFADAEAFQAHAGAEAGIAEAMQADAKAAALIAAAEIAAAEQAAAKgDAIQgCAKgGAHQgFAIgIAGIgEADQgFAEgHACQgJAFgJABIgSACIgMgFgABrBtIAAgWIAtAAIAAiSIgtAAIAAgUIAUgBQAXgIADgFQAFgHAAgJIAXAAIAADEIAsAAIAAAWIh2AAgAgSBtIAAgpIAiAAIAAApIgiAAgAjsBtIAAgeIAggbQAPgNANgNQAcgbALgQQAKgQAAgSQgWglgVAAQgNAAgPAGQgPAEgPAJQgCgOAAgQQALgFARgEQARgEARgBQAhAAATAQQATAQAAAcQAAANgDALQgEAKgGAKQgFAJgIAIIgSATQgQAQgRAOIgfAbIB1AAIAAAZIiUAAgAE9BYIgFABIgDAAIgHgHQgGgGgGgKQgGgMgFgRIgCgLQgGgHgEgIIAAgLIAEgFIAIgKIACgCIAAABIAAAYIAAAKQABAEADAEIAHAKIAHAKIADAEIADAFIAFAIIAFALIAGAMIAAADIAAABIgEgCgAgSgMIAAgqIAiAAIAAAqIgiAAg");
	this.shape_51.setTransform(363.95,489.65);

	this.shape_52 = new cjs.Shape();
	this.shape_52.graphics.f("#333333").s().p("AFGBsQgNgEgKgKQgNgNgHgTQgGgVAAgcQgBgcAHgWQAGgWAOgSQAMgQAVgKQAUgJAcAAIAOABIALACIAAAcIgBAAIgMgEQgIgCgJAAQggAAgTAUQgSATgDAiQAMgIAMgEQAMgDAQAAQAOAAALACQAKADALAHQANAKAGAMQAHAOAAATQAAAhgWAVQgWAWggAAQgPgBgOgFgAFIgCQgKACgMAGIAAAGIAAAHQAAAYAFANQAEAOAJAHQAHAGAIAEQAIACAIABQAWgBAMgMQAMgOAAgYQAAgNgEgJQgEgJgJgHQgHgDgIgCQgIgCgJAAQgMAAgMAEgAmcBWQgSgcAAg6QAAg5ASgbQATgdAmAAQAoAAASAdQASAcAAA4QAAA6gSAcQgTAcgnAAQgmAAgTgcgAl5hSQgJAFgGAMQgEAKgCASQgCASAAATQAAAXACAPQABAQAFAMQAFAMAJAFQAJAHAOAAQAOAAAJgHQAJgFAGgMQAEgLACgRQACgQAAgWQAAgWgCgQQgCgQgEgLQgGgMgJgFQgJgHgOAAQgOAAgIAHgABrBtIAAgWIAtAAIAAiSIgtAAIAAgUIATgBQALgCAGgCQAGgEAEgFQAEgHAAgJIAXAAIAADEIAtAAIAAAWgAgSBtIAAgpIAiAAIAAApgAjsBtIAAgeIAfgbQAPgNANgNQAdgbAKgQQALgQAAgSQAAgRgMgKQgLgJgUgBQgNAAgPAGQgQAEgPAJIgCAAIAAgeQALgFARgEQASgEAQgBQAhAAAUAQQASAQAAAcQAAANgCALQgEAKgGAKQgFAJgJAIIgSATQgQAQgRAOIgeAbIB0AAIAAAZgAgSgMIAAgqIAiAAIAAAqg");
	this.shape_52.setTransform(364,489.65);

	this.shape_53 = new cjs.Shape();
	this.shape_53.graphics.f("#333333").s().p("AmWBWQgTgcABg6QAAg5ASgbQASgdAnAAQAnAAASAdQATAcgBA4QAAA6gSAcQgTAcgmAAQgnAAgSgcgAl0hSQgJAFgMAoQgCASABATQgBAXACAPQACAQAFAMQAFAMAIAFQAJAHAPAAQAOAAAJgHQAJgFAFgMQAFgLACgRQABgQABgWQgBgWgBgQQgCgQgFgLQgFgMgJgFQgJgHgOAAQgOAAgJAHgAFHBtIgBgBQgJgGgHgKQgFgHgEgJIAGAGIAHAHIADAAIAFgBIAGACQAJgCAIgFQARgJAJgSIAAgEIAAgIQgEgIgGgFIgCgCQgEgLgGgJQgGgIgGgEQgHgGgHgEIgSgJIAHgXIABgCQgEgRACgOQACgHADgFIAKgLIAHgDIANgEQAQgDARAAIAOAAIALACIADAWIAAAAIgJgCIgLgCQgVAAgMAQIgCACQgMARgDAbIgBADQAJgEAJgCQAIgCAMACQAKACAJADQAIADAIAIQAJAJAFAMQACAHAAALIAAAMQgDAggTAVQgRASgWAGIgKABQgNgBgOgDgABwBtIAAgWIAtAAIAAiSIgtAAIAAgUIAUgBQAXgIADgFQAFgHAAgJIAXAAIAADEIAsAAIAAAWIh2AAgAgNBtIAAgpIAiAAIAAApIgiAAgAjnBtIAAgeIAggbQAPgNANgNQAcgbALgQQAKgQAAgSQgWglgVAAQgNAAgPAGQgPAEgPAJQgCgOAAgQQALgFARgEQARgEARgBQAhAAATAQQATAQAAAcQAAANgDALQgEAKgGAKQgFAJgIAIIgSATQgQAQgRAOIgfAbIB1AAIAAAZIiUAAgAgNgMIAAgqIAiAAIAAAqIgiAAg");
	this.shape_53.setTransform(363.45,489.65);

	this.shape_54 = new cjs.Shape();
	this.shape_54.graphics.f("#333333").s().p("AmSBWQgSgcAAg6QAAg5ATgbQASgdAnAAQAnAAASAdQASAcAAA4QAAA6gSAcQgTAcgmAAQgnAAgTgcgAlvhSQgJAFgMAoQgCASAAATQAAAXACAPQABAQAGAMQAEAMAJAFQAJAHAPAAQAOAAAJgHQAJgFAFgMQAFgLACgRQABgQAAgWQAAgWgBgQQgCgQgFgLQgGgMgIgFQgJgHgOAAQgOAAgJAHgAFgBvQgNAAgNgCIgBgBQgFgHgEgKIgCgGQAPgHAMgIIAAgGIAAgKQgIgFgJgEIgEgBIgFgUIAEgPQAJghAMgdIABgDIgVgXIgHgKIAHgOIAJgCIAPgDQAPgCAQAAIAMAAIAKACIAHAQIgEgCIgGgCQgLAAgEANIgBABQgKARgCAYIgBAEQAGgCAFABIANAEQAHADAFAEQAFAEAGAHQAGAJACALQABAIgBAJIgCAMQgFAdgSAWQgPASgSAJIgKAAgAB1BtIAAgWIAtAAIAAiSIgtAAIAAgUIAUgBQAWgIAEgFQAEgHABgJIAXAAIAADEIAsAAIAAAWIh2AAgAgIBtIAAgpIAiAAIAAApIgiAAgAjiBtIAAgeIAfgbQAQgNANgNQAcgbAKgQQALgQAAgSQgXglgUAAQgNAAgPAGQgQAEgPAJQgBgOAAgQQAKgFASgEQARgEAQgBQAiAAATAQQATAQAAAcQAAANgDALQgEAKgGAKQgFAJgIAIIgTATQgPAQgRAOIgfAbIB1AAIAAAZIiUAAgAgIgMIAAgqIAiAAIAAAqIgiAAg");
	this.shape_54.setTransform(362.9583,489.65);

	this.shape_55 = new cjs.Shape();
	this.shape_55.graphics.f("#333333").s().p("AmNBWQgSgcAAg6QAAg5ASgbQASgdAnAAQAoAAASAdQASAcAAA4QAAA6gTAcQgSAcgnAAQgnAAgSgcgAlqhSQgKAFgMAoQgBASAAATQAAAXABAPQACAQAFAMQAFAMAJAFQAJAHAOAAQAOAAAJgHQAJgFAFgMQAFgLACgRQACgQAAgWQAAgWgCgQQgCgQgFgLQgFgMgJgFQgJgHgOAAQgOAAgIAHgAFFBtIAAgBQgCgJAAgKQgBgNABgQIAEgVIANghQANgiAPgiIACgCIgqgQIgSgHIAEgSIAKgBIASgCQANgCAPABIAMAAIAIABIALALQAAgBAAAAQAAgBAAAAQAAAAAAAAQAAAAAAAAIAAAAQAAAAABABQAAAAAAAAQAAAAAAABQgBAAAAAAIAAAAIACAGIgBAAQgGASgBAUIgCAFIAFAEIAGAIIAGAJIAFALQACAKgBAKIgCAPIgDAMQgHAagQAXQgNASgQAMIgJABQgNAAgMgCgAB5BtIAAgWIAuAAIAAiSIguAAIAAgUIAUgBQAXgIAEgFQAEgHAAgJIAXAAIAADEIAtAAIAAABIgEAAIgKAAIADALIALAAIAAAKIh3AAgAgEBtIAAgpIAiAAIAAApIgiAAgAjdBtIAAgeIAfgbQAPgNANgNQAdgbAKgQQAKgQAAgSQgWglgUAAQgNAAgQAGQgPAEgPAJQgCgOAAgQQALgFARgEQARgEARgBQAhAAATAQQATAQAAAcQAAANgDALQgDAKgGAKQgGAJgIAIIgSATQgQAQgRAOIgfAbIB1AAIAAAZIiTAAgAgEgMIAAgqIAiAAIAAAqIgiAAg");
	this.shape_55.setTransform(362.53,489.65);

	this.shape_56 = new cjs.Shape();
	this.shape_56.graphics.f("#333333").s().p("AmRBWQgSgcAAg6QAAg5ATgbQASgdAnAAQAnAAASAdQASAcAAA4QAAA6gSAcQgTAcgmAAQgnAAgTgcgAluhSQgJAFgMAoQgCASAAATQAAAXACAPQABAQAGAMQAEAMAJAFQAJAHAPAAQAOAAAJgHQAJgFAFgMQAFgLACgRQABgQAAgWQAAgWgBgQQgCgQgFgLQgGgMgIgFQgJgHgOAAQgOAAgJAHgAFUBuIgZgBIABgBIAFgUIAHgcIAHgUIASgkQARglASglIADgDIg+gIIgfgDIACgXIAMAAIATgBIAbgBIAKABIAIAAIAOAGIABAAIAEgCIAFAAQAJAAALAEIgBABQgDAQAAATIgCAEIgCAJIgBANIgBALIgBALQgBAKgDAJIgEAOIgFALQgJAZgOAWQgMATgNAQIgIAAgAgHBtIAAgpIAiAAIAAApIgiAAgAjhBtIAAgeIAfgbQAQgNANgNQAcgbAKgQQALgQAAgSQgXglgUAAQgNAAgPAGQgQAEgPAJQgBgOAAgQQAKgFASgEQARgEAQgBQAiAAATAQQATAQAAAcQAAANgDALQgEAKgGAKQgFAJgIAIIgTATQgPAQgRAOIgfAbIB1AAIAAAZIiUAAgAgHgMIAAgqIAiAAIAAAqIgiAAgACjgpIAAgSIgFAAIgoAAIAAgUIAUgBQAWgIAEgFQAEgHABgJIAXAAIAAAmIAAAiIgdgEg");
	this.shape_56.setTransform(362.875,489.65);

	this.shape_57 = new cjs.Shape();
	this.shape_57.graphics.f("#333333").s().p("AmbBWQgSgcAAg6QAAg5ATgbQASgdAnAAQAnAAASAdQASAcAAA4QAAA6gSAcQgTAcgmAAQgnAAgTgcgAl4hSQgJAFgFAMQgFAKgCASQgCASAAATQAAAXACAPQABAQAGAMQAEAMAJAFQAJAHAPAAQAOAAAJgHQAJgFAFgMQAFgLACgRQABgQAAgWQAAgWgBgQQgCgQgFgLQgGgMgIgFQgJgHgOAAQgOAAgJAHgAErBtIBqi/Ih9AAIAAgaICWAAIAAAhIhjC4gABsBtIAAgWIAtAAIAAiSIgtAAIAAgUIAUgBQAKgCAGgCQAGgEAEgFQAEgHABgJIAXAAIAADEIAsAAIAAAWgAgRBtIAAgpIAiAAIAAApgAjrBtIAAgeIAfgbQAQgNANgNQAcgbAKgQQALgQAAgSQAAgRgLgKQgMgJgUgBQgNAAgPAGQgQAEgPAJIgBAAIAAgeQAKgFASgEQARgEAQgBQAiAAATAQQATAQAAAcQAAANgDALQgEAKgGAKQgFAJgIAIIgTATQgPAQgRAOIgfAbIB1AAIAAAZgAgRgMIAAgqIAiAAIAAAqg");
	this.shape_57.setTransform(363.875,489.65);

	this.instance_5 = new lib.CachedBmp_8();
	this.instance_5.setTransform(387.65,468.4,0.5,0.5);

	this.instance_6 = new lib.CachedBmp_7();
	this.instance_6.setTransform(368.6,468.4,0.5,0.5);

	this.instance_7 = new lib.CachedBmp_6();
	this.instance_7.setTransform(355,468.4,0.5,0.5);

	this.instance_8 = new lib.CachedBmp_5();
	this.instance_8.setTransform(335.95,468.4,0.5,0.5);

	this.instance_9 = new lib.CachedBmp_4();
	this.instance_9.setTransform(316.9,468.4,0.5,0.5);

	this.instance_10 = new lib.CachedBmp_13();
	this.instance_10.setTransform(387.65,468.4,0.5,0.5);

	this.instance_11 = new lib.CachedBmp_12();
	this.instance_11.setTransform(368.6,468.4,0.5,0.5);

	this.instance_12 = new lib.CachedBmp_11();
	this.instance_12.setTransform(355,468.4,0.5,0.5);

	this.instance_13 = new lib.CachedBmp_10();
	this.instance_13.setTransform(335.95,468.4,0.5,0.5);

	this.instance_14 = new lib.CachedBmp_9();
	this.instance_14.setTransform(316.9,468.4,0.5,0.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_4}]}).to({state:[{t:this.shape_26}]},49).to({state:[{t:this.shape_26}]},17).to({state:[{t:this.shape_27}]},1).to({state:[{t:this.shape_28}]},1).to({state:[{t:this.shape_29}]},1).to({state:[{t:this.shape_30}]},1).to({state:[{t:this.shape_31}]},1).to({state:[{t:this.shape_31}]},16).to({state:[{t:this.shape_32}]},1).to({state:[{t:this.shape_33}]},1).to({state:[{t:this.shape_34}]},1).to({state:[{t:this.shape_35}]},1).to({state:[{t:this.shape_36}]},1).to({state:[{t:this.shape_37}]},1).to({state:[{t:this.shape_37}]},17).to({state:[{t:this.shape_38}]},1).to({state:[{t:this.shape_39}]},1).to({state:[{t:this.shape_40}]},1).to({state:[{t:this.shape_41}]},1).to({state:[{t:this.shape_42}]},1).to({state:[{t:this.shape_42}]},17).to({state:[{t:this.shape_43}]},1).to({state:[{t:this.shape_44}]},1).to({state:[{t:this.shape_45}]},1).to({state:[{t:this.shape_46}]},1).to({state:[{t:this.shape_47}]},1).to({state:[{t:this.shape_47}]},17).to({state:[{t:this.shape_48}]},1).to({state:[{t:this.shape_49}]},1).to({state:[{t:this.shape_50}]},1).to({state:[{t:this.shape_51}]},1).to({state:[{t:this.shape_52}]},1).to({state:[{t:this.shape_52}]},17).to({state:[{t:this.shape_53}]},1).to({state:[{t:this.shape_54}]},1).to({state:[{t:this.shape_55}]},1).to({state:[{t:this.shape_56}]},1).to({state:[{t:this.shape_57}]},1).to({state:[{t:this.instance_9},{t:this.instance_8},{t:this.instance_7},{t:this.instance_6},{t:this.instance_5}]},22).to({state:[{t:this.instance_14},{t:this.instance_13},{t:this.instance_12},{t:this.instance_11},{t:this.instance_10}]},15).wait(11));

	// подложка
	this.shape_58 = new cjs.Shape();
	this.shape_58.graphics.f("#FFFFFF").s().p("A0hUiQohogAAsCQAAsBIhogQIgogMBgBQMCABIgIgQIhIggBMBQABMCohIgQogIhsCgBQsBABogohg");
	this.shape_58.setTransform(367.85,264.1);

	this.timeline.addTween(cjs.Tween.get(this.shape_58).wait(229));

	// фон
	this.shape_59 = new cjs.Shape();
	this.shape_59.graphics.f("#CCCCCC").s().p("Eg4UA+lMAAAh9JMBwoAAAMAAAB9Jg");
	this.shape_59.setTransform(360.4,400.525);

	this.timeline.addTween(cjs.Tween.get(this.shape_59).wait(229));

	this._renderFirstFrame();

}).prototype = p = new lib.AnMovieClip();
p.nominalBounds = new cjs.Rectangle(360,395,360.9,406.1);
// library properties:
lib.properties = {
	id: '2A7093272A149A45BCBB331436E465BC',
	width: 720,
	height: 802,
	fps: 24,
	color: "#FFFFFF",
	opacity: 1.00,
	manifest: [
		{src:"images/RECOVER_пластинка_atlas_1.png?1681940453687", id:"RECOVER_пластинка_atlas_1"},
		{src:"images/RECOVER_пластинка_atlas_2.png?1681940453687", id:"RECOVER_пластинка_atlas_2"},
		{src:"sounds/_04715.mp3?1681940453763", id:"_04715"},
		{src:"sounds/_04715mp3copy.mp3?1681940453763", id:"_04715mp3copy"},
		{src:"sounds/nazvonokcom_nervyjarcheitepleemp3copy.mp3?1681940453763", id:"nazvonokcom_nervyjarcheitepleemp3copy"}
	],
	preloads: []
};



// bootstrap callback support:

(lib.Stage = function(canvas) {
	createjs.Stage.call(this, canvas);
}).prototype = p = new createjs.Stage();

p.setAutoPlay = function(autoPlay) {
	this.tickEnabled = autoPlay;
}
p.play = function() { this.tickEnabled = true; this.getChildAt(0).gotoAndPlay(this.getTimelinePosition()) }
p.stop = function(ms) { if(ms) this.seek(ms); this.tickEnabled = false; }
p.seek = function(ms) { this.tickEnabled = true; this.getChildAt(0).gotoAndStop(lib.properties.fps * ms / 1000); }
p.getDuration = function() { return this.getChildAt(0).totalFrames / lib.properties.fps * 1000; }

p.getTimelinePosition = function() { return this.getChildAt(0).currentFrame / lib.properties.fps * 1000; }

an.bootcompsLoaded = an.bootcompsLoaded || [];
if(!an.bootstrapListeners) {
	an.bootstrapListeners=[];
}

an.bootstrapCallback=function(fnCallback) {
	an.bootstrapListeners.push(fnCallback);
	if(an.bootcompsLoaded.length > 0) {
		for(var i=0; i<an.bootcompsLoaded.length; ++i) {
			fnCallback(an.bootcompsLoaded[i]);
		}
	}
};

an.compositions = an.compositions || {};
an.compositions['2A7093272A149A45BCBB331436E465BC'] = {
	getStage: function() { return exportRoot.stage; },
	getLibrary: function() { return lib; },
	getSpriteSheet: function() { return ss; },
	getImages: function() { return img; }
};

an.compositionLoaded = function(id) {
	an.bootcompsLoaded.push(id);
	for(var j=0; j<an.bootstrapListeners.length; j++) {
		an.bootstrapListeners[j](id);
	}
}

an.getComposition = function(id) {
	return an.compositions[id];
}


an.makeResponsive = function(isResp, respDim, isScale, scaleType, domContainers) {		
	var lastW, lastH, lastS=1;		
	window.addEventListener('resize', resizeCanvas);		
	resizeCanvas();		
	function resizeCanvas() {			
		var w = lib.properties.width, h = lib.properties.height;			
		var iw = window.innerWidth, ih=window.innerHeight;			
		var pRatio = window.devicePixelRatio || 1, xRatio=iw/w, yRatio=ih/h, sRatio=1;			
		if(isResp) {                
			if((respDim=='width'&&lastW==iw) || (respDim=='height'&&lastH==ih)) {                    
				sRatio = lastS;                
			}				
			else if(!isScale) {					
				if(iw<w || ih<h)						
					sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==1) {					
				sRatio = Math.min(xRatio, yRatio);				
			}				
			else if(scaleType==2) {					
				sRatio = Math.max(xRatio, yRatio);				
			}			
		}
		domContainers[0].width = w * pRatio * sRatio;			
		domContainers[0].height = h * pRatio * sRatio;
		domContainers.forEach(function(container) {				
			container.style.width = w * sRatio + 'px';				
			container.style.height = h * sRatio + 'px';			
		});
		stage.scaleX = pRatio*sRatio;			
		stage.scaleY = pRatio*sRatio;
		lastW = iw; lastH = ih; lastS = sRatio;            
		stage.tickOnUpdate = false;            
		stage.update();            
		stage.tickOnUpdate = true;		
	}
}
an.handleSoundStreamOnTick = function(event) {
	if(!event.paused){
		var stageChild = stage.getChildAt(0);
		if(!stageChild.paused || stageChild.ignorePause){
			stageChild.syncStreamSounds();
		}
	}
}
an.handleFilterCache = function(event) {
	if(!event.paused){
		var target = event.target;
		if(target){
			if(target.filterCacheList){
				for(var index = 0; index < target.filterCacheList.length ; index++){
					var cacheInst = target.filterCacheList[index];
					if((cacheInst.startFrame <= target.currentFrame) && (target.currentFrame <= cacheInst.endFrame)){
						cacheInst.instance.cache(cacheInst.x, cacheInst.y, cacheInst.w, cacheInst.h);
					}
				}
			}
		}
	}
}


})(createjs = createjs||{}, AdobeAn = AdobeAn||{});
var createjs, AdobeAn;